version: '3.9'

services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:latest
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /data/rdesktop/data:/config #optional
    ports:
      - 3389:3389
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

# default user/pass : abc/abc
# Change password
# docker exec -it rdesktop passwd abc